"""Intent-aware routing for conversation outcomes and response strategy."""

from __future__ import annotations

from dataclasses import dataclass

from core.models import ConversationState, IntentType


@dataclass(slots=True)
class RouteDecision:
    """Decision generated by intent router."""

    next_state: ConversationState
    next_action: str
    priority: str


class IntentRouter:
    """Maps intent and conversation state to workflow actions."""

    def route(
        self,
        intent: IntentType,
        current_state: ConversationState,
        propensity_score: float,
    ) -> RouteDecision:
        """Return route decision for downstream handlers."""

        if intent == IntentType.NOT_INTERESTED:
            return RouteDecision(next_state=ConversationState.CLOSED, next_action="unsubscribe", priority="high")

        if propensity_score >= 0.8:
            return RouteDecision(next_state=ConversationState.HOT_LEAD, next_action="notify_agent", priority="high")

        if intent in {IntentType.BUYER, IntentType.SELLER}:
            return RouteDecision(
                next_state=ConversationState.QUALIFYING,
                next_action="ask_qualifying_question",
                priority="medium",
            )

        if current_state == ConversationState.NEW:
            return RouteDecision(
                next_state=ConversationState.NURTURING,
                next_action="share_relevant_listing",
                priority="medium",
            )

        return RouteDecision(next_state=ConversationState.NURTURING, next_action="continue_nurture", priority="low")
